### PR TITLE
WIP Improve README's clarity of example data flow

### PR DESCRIPTION
**Pull request by r4j4h**
I'm not sure if this is really better or just wordier, but when glancing it over I felt like it just starts out using TodoList and TodoStore without really showing how they fit together in relation to RiotControl itself and how simple they are. I think most people will get it, esp. if they are familiar with React but new people might not.

### CODE REVIEW

**Comment by a-moses** [comment]
@r4j4h   :+1:  

more documentation needed (Please...)

**Comment by r4j4h** [comment]
I am glad you approve and if I get some spare time I will submit more :)

**Comment by jimsparkman** [comment]
Thanks for this, I will try to merge this in the evening. I will probably rework it slightly.

**Comment by r4j4h** [comment]
@jimsparkman Great! Thank you :)

**Comment by a-moses** [comment]
@jimsparkman  Thank you !

**Comment by jimsparkman** [comment]
Merged and formatted, thoughts?

**Pull request merged**
